## Jekyll Configuration 

# Permalinks

permalink: pretty
relative_permalinks: true

# General Info

title: The Egregious Nerd
tagline: Where Code Comes to Die
url: http://pavelrogala.github.io
pagination: 1
#baseurl: "http://pavelrogala.github.io"
timezone: RS

# About/Contact
author:
  name: Pavel Rogala
  url: https://onename.com/pavelrogala
  email: pavel.rogala@gmail.com


